# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  aggregatormicroservice:
    image: aggregatormicroservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80